name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dask
  - distributed
  - pandas
  - pyarrow
  - pytest
  - grpcio
  - pandas-gbq
  - google-cloud-bigquery>=2.11.0
  - google-cloud-bigquery-storage