name: test-environment
channels:
  - conda-forge
dependencies:
  - python=3.7
  - dask
  - distributed
  - pandas
  - pyarrow
  - pytest
  - grpcio
  # Including grpcio-status as a temporary workaround for
  # https://github.com/googleapis/python-api-core/issues/301
  - grpcio-status
  - google-cloud-bigquery>=2.11.0
  - google-cloud-bigquery-storage