name: test-environment
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.11
  - dask >=2024.3.0
  - distributed
  - pandas
  - pyarrow
  - pytest
  - gcsfs
  - google-cloud-bigquery>=2.11.0
  - google-cloud-bigquery-storage
  - pip
  - pip:
    - git+https://github.com/dask/dask
